package com.lixing.siitep.mapper;

import com.lixing.siitep.entity.TbDayrpt;
import com.lixing.siitep.entity.TbDayrptExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbDayrptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dayrpt
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    long countByExample(TbDayrptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dayrpt
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    int deleteByExample(TbDayrptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dayrpt
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dayrpt
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    int insert(TbDayrpt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dayrpt
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    int insertSelective(TbDayrpt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dayrpt
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    List<TbDayrpt> selectByExample(TbDayrptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dayrpt
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    TbDayrpt selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dayrpt
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    int updateByExampleSelective(@Param("record") TbDayrpt record, @Param("example") TbDayrptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dayrpt
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    int updateByExample(@Param("record") TbDayrpt record, @Param("example") TbDayrptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dayrpt
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    int updateByPrimaryKeySelective(TbDayrpt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dayrpt
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    int updateByPrimaryKey(TbDayrpt record);

}