package com.lixing.siitep.mapper;

import com.lixing.siitep.entity.TbGuide;
import com.lixing.siitep.entity.TbGuideExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbGuideMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guide
     *
     * @mbg.generated Mon Feb 24 11:02:36 CST 2020
     */
    long countByExample(TbGuideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guide
     *
     * @mbg.generated Mon Feb 24 11:02:36 CST 2020
     */
    int deleteByExample(TbGuideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guide
     *
     * @mbg.generated Mon Feb 24 11:02:36 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guide
     *
     * @mbg.generated Mon Feb 24 11:02:36 CST 2020
     */
    int insert(TbGuide record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guide
     *
     * @mbg.generated Mon Feb 24 11:02:36 CST 2020
     */
    int insertSelective(TbGuide record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guide
     *
     * @mbg.generated Mon Feb 24 11:02:36 CST 2020
     */
    List<TbGuide> selectByExample(TbGuideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guide
     *
     * @mbg.generated Mon Feb 24 11:02:36 CST 2020
     */
    TbGuide selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guide
     *
     * @mbg.generated Mon Feb 24 11:02:36 CST 2020
     */
    int updateByExampleSelective(@Param("record") TbGuide record, @Param("example") TbGuideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guide
     *
     * @mbg.generated Mon Feb 24 11:02:36 CST 2020
     */
    int updateByExample(@Param("record") TbGuide record, @Param("example") TbGuideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guide
     *
     * @mbg.generated Mon Feb 24 11:02:36 CST 2020
     */
    int updateByPrimaryKeySelective(TbGuide record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guide
     *
     * @mbg.generated Mon Feb 24 11:02:36 CST 2020
     */
    int updateByPrimaryKey(TbGuide record);
}