package com.lixing.siitep.mapper;

import com.lixing.siitep.entity.TblRecord;
import com.lixing.siitep.entity.TblRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_record
     *
     * @mbg.generated Mon Feb 24 11:14:15 CST 2020
     */
    long countByExample(TblRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_record
     *
     * @mbg.generated Mon Feb 24 11:14:15 CST 2020
     */
    int deleteByExample(TblRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_record
     *
     * @mbg.generated Mon Feb 24 11:14:15 CST 2020
     */
    int insert(TblRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_record
     *
     * @mbg.generated Mon Feb 24 11:14:15 CST 2020
     */
    int insertSelective(TblRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_record
     *
     * @mbg.generated Mon Feb 24 11:14:15 CST 2020
     */
    List<TblRecord> selectByExample(TblRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_record
     *
     * @mbg.generated Mon Feb 24 11:14:15 CST 2020
     */
    int updateByExampleSelective(@Param("record") TblRecord record, @Param("example") TblRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_record
     *
     * @mbg.generated Mon Feb 24 11:14:15 CST 2020
     */
    int updateByExample(@Param("record") TblRecord record, @Param("example") TblRecordExample example);

    // 查找最新的日报表名
    String selectTableName();
    //获取一周的表
    List<String> OneWeekTable();


}