package com.lixing.siitep.mapper;

import com.lixing.siitep.entity.TbPictures;
import com.lixing.siitep.entity.TbPicturesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbPicturesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pictures
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    long countByExample(TbPicturesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pictures
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    int deleteByExample(TbPicturesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pictures
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pictures
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    int insert(TbPictures record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pictures
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    int insertSelective(TbPictures record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pictures
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    List<TbPictures> selectByExample(TbPicturesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pictures
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    TbPictures selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pictures
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    int updateByExampleSelective(@Param("record") TbPictures record, @Param("example") TbPicturesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pictures
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    int updateByExample(@Param("record") TbPictures record, @Param("example") TbPicturesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pictures
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    int updateByPrimaryKeySelective(TbPictures record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pictures
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    int updateByPrimaryKey(TbPictures record);

    List<TbPictures> selectByType(int type);

}