server:
  port: 8082
spring:
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://47.101.141.93:3306/dcmdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
