package com.lixing.siitep.entity;

import lombok.Data;

import java.util.Date;

@Data
public class TbDayrpt {
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dayrpt.s_name
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    private String sName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dayrpt.s_id
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    private String sId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dayrpt.c_name
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    private String cName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dayrpt.dept_name
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    private String deptName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dayrpt.temperature
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    private Float temperature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dayrpt.is_contact
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    private Integer isContact;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dayrpt.is_pass
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    private Integer isPass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dayrpt.location_province
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    private String locationProvince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dayrpt.location_city
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    private String locationCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dayrpt.is_isolated
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    private Integer isIsolated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dayrpt.quarantine
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    private Integer quarantine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dayrpt.how_long
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    private Integer howLong;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dayrpt.up_time
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */

    private Date upTime;

}