package com.lixing.siitep.entity;

import lombok.Data;

@Data
public class TbDiagnosis {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diagnosis.id
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diagnosis.h5url
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    private String h5url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diagnosis.title
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    private String title;

}