package com.lixing.siitep.entity;

public class TbDiagnosis {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diagnosis.id
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diagnosis.h5url
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    private String h5url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diagnosis.title
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    private String title;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diagnosis.id
     *
     * @return the value of tb_diagnosis.id
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diagnosis.id
     *
     * @param id the value for tb_diagnosis.id
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diagnosis.h5url
     *
     * @return the value of tb_diagnosis.h5url
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    public String getH5url() {
        return h5url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diagnosis.h5url
     *
     * @param h5url the value for tb_diagnosis.h5url
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    public void setH5url(String h5url) {
        this.h5url = h5url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diagnosis.title
     *
     * @return the value of tb_diagnosis.title
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diagnosis.title
     *
     * @param title the value for tb_diagnosis.title
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    public void setTitle(String title) {
        this.title = title;
    }
}