package com.lixing.siitep.entity;

import lombok.Data;

@Data
public class TbGuide {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_guide.id
     *
     * @mbg.generated Mon Feb 24 11:02:36 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_guide.h5url
     *
     * @mbg.generated Mon Feb 24 11:02:36 CST 2020
     */
    private String h5url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_guide.title
     *
     * @mbg.generated Mon Feb 24 11:02:36 CST 2020
     */
    private String title;

}