package com.lixing.siitep.entity;

public class TbPictures {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pictures.id
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pictures.type
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pictures.img
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    private String img;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pictures.title
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    private String title;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_pictures.id
     *
     * @return the value of tb_pictures.id
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_pictures.id
     *
     * @param id the value for tb_pictures.id
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_pictures.type
     *
     * @return the value of tb_pictures.type
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_pictures.type
     *
     * @param type the value for tb_pictures.type
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_pictures.img
     *
     * @return the value of tb_pictures.img
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_pictures.img
     *
     * @param img the value for tb_pictures.img
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    public void setImg(String img) {
        this.img = img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_pictures.title
     *
     * @return the value of tb_pictures.title
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_pictures.title
     *
     * @param title the value for tb_pictures.title
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    public void setTitle(String title) {
        this.title = title;
    }
}