package com.lixing.siitep.entity;

import lombok.Data;

@Data
public class TbPictures {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pictures.id
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pictures.type
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pictures.img
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    private String img;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pictures.title
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    private String title;


}