package com.lixing.siitep.entity;

public class TbRumor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rumor.id
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rumor.date_rumor
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    private String dateRumor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rumor.explain_rumor
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    private String explainRumor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rumor.title
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    private String title;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rumor.id
     *
     * @return the value of tb_rumor.id
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rumor.id
     *
     * @param id the value for tb_rumor.id
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rumor.date_rumor
     *
     * @return the value of tb_rumor.date_rumor
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    public String getDateRumor() {
        return dateRumor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rumor.date_rumor
     *
     * @param dateRumor the value for tb_rumor.date_rumor
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    public void setDateRumor(String dateRumor) {
        this.dateRumor = dateRumor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rumor.explain_rumor
     *
     * @return the value of tb_rumor.explain_rumor
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    public String getExplainRumor() {
        return explainRumor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rumor.explain_rumor
     *
     * @param explainRumor the value for tb_rumor.explain_rumor
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    public void setExplainRumor(String explainRumor) {
        this.explainRumor = explainRumor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rumor.title
     *
     * @return the value of tb_rumor.title
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rumor.title
     *
     * @param title the value for tb_rumor.title
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    public void setTitle(String title) {
        this.title = title;
    }
}