package com.lixing.siitep.entity;

import lombok.Data;

@Data
public class TbRumor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rumor.id
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rumor.date_rumor
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    private String dateRumor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rumor.explain_rumor
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    private String explainRumor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rumor.title
     *
     * @mbg.generated Mon Feb 24 09:59:27 CST 2020
     */
    private String title;

}